filename = 'all_hist.txt'
leapremoved = 0
datastartyear=1970
dataendyear =2011
init_year=2000
init_month = 8
init_day = 1
periodstart_year = 2000
periodstart_month = 1
periodstart_day = 1
periodend_year = 2001
periodend_month = 12
periodend_day = 31
climstartyear = 1970
climendyear = 2009
leapinit = 1
climatological_metric_file = "histmetric.txt"
forecast_metric_file = "forecastmetric.txt"
ensemble_metric_file = "ensemble.txt"
